sudo: false
language: ruby
cache:
  directories:
  - vendor/bundle
env: # IAM: travis-s3
  secure: F0pNzaT5lip6Xq2ITi+OP+oy16Vf7gXYZS05Oy7zotiIeyPY7GpV3wi6nXOi3CZ0xwPQzyhqp5UeNnC8THAqNYDtDLqQBF4DaU6urk6b8iRr8SnHw7ESm1tq3GRlBARCLxbP2x+nf9tYla4RLB64L5nCUiIYLsLGZ8u5XMlugIE=
install:
- bundle install --deployment --retry 3
- npm install bower
- bower install
- pip install --user awscli
script:
- bundle exec rake
